title:            Clean+Simple Theme
description:      Something...
       

future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

include: 
  - .htaccess
  
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: liweiwu-com
